// src/components/Error.tsx
import React from "react";

import { Page } from './Page';

export function Error() {
    return <Page>
        <h1>404: Not found</h1>

        <p>This page or file doesn’t exist.</p>

        <p>There used to be more stuff on this website, but it’s gone at the moment for expediency’s sake. If you’re looking for something in particular, <a href="mailto:g@hslp.ca">get in touch</a> and I might be able to help.</p>

        <p><a href="/">Click here</a> to navigate to the homepage.</p>
    </Page>;
}

// components/Error.svelte
<script context="module">
    import Layout from './Layout.svelte';
    import Page from './Page.svelte';
</script>

<Layout>
    <Page>
        <h1>404: Not found</h1>
        <p>This page or file doesn’t exist.</p>
        <p>There used to be more stuff on this website, but it’s gone at the moment for expediency’s sake. If you’re looking for something in particular, <a href="mailto:g@hslp.ca">get in touch</a> and I might be able to help.</p>
        <p><a href="/">Click here</a> to navigate to the homepage.</p>
    </Page>
</Layout>
