// components/Home.svelte
<script context="module">
    import Layout from './Layout.svelte';
    import Page from './Page.svelte';
</script>

<script>
    export let canonicalUrl;
</script>

<Layout canonicalUrl={canonicalUrl}>
    <Page>
        <h1 class="name">Grant Heaslip</h1>

        <p>I’m a web developer, wannabe polymath, and video game nerd living in Toronto, Canada. I still don’t have much of anything figured out.</p>

        <p>If you want to get in touch, send an e-mail to <a href="mailto:g@hslp.ca">g@hslp.ca</a>.</p>
    </Page>
</Layout>

// src/components/Home.tsx
import React from "react";

import { Page } from './Page';

export function Home() {
    return <Page>
        <h1>Grant Heaslip</h1>

        <p>I’m a web developer, wannabe polymath, and video game nerd living in Toronto, Canada. I still don’t have much of anything figured out.</p>

        <p>If you want to get in touch, send an e-mail to <a href="mailto:g@hslp.ca">g@hslp.ca</a>.</p>
    </Page>;
}
